name: Build

on:
  workflow_dispatch:

jobs:
  build-on-linux:
    name: Build on Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download
        run: wget http://www.atnf.csiro.au/people/mcalabre/WCS/wcslib-8.3.tar.bz2 -O wcslib.tar.bz2

      - name: Unzip
        run: bzcat wcslib.tar.bz2 | tar pvxf -

      - name: Configure
        working-directory: wcslib-8.3
        run: ./configure

      - name: Make
        working-directory: wcslib-8.3
        run: make build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: libwcs
          path: |
            wcslib-8.3/C/libwcs.so.8.3
          retention-days: 7

  build-on-windows:
    name: Build on Windows
    runs-on: windows-latest
    needs: build-on-linux

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          install: mingw-w64-x86_64-openssl

      - name: Install GCC
        run: pacman --noconfirm -S mingw-w64-x86_64-gcc diffutils make

      - name: Checkout
        uses: actions/checkout@v4

      - name: Download
        run: wget http://www.atnf.csiro.au/people/mcalabre/WCS/wcslib-8.3.tar.bz2 -O wcslib.tar.bz2

      - name: Unzip
        run: bzcat wcslib.tar.bz2 | tar pvxf -

      - name: Configure
        working-directory: wcslib-8.3
        run: ./configure

      - name: Make
        working-directory: wcslib-8.3
        run: make build CFLAGS=-DNO_OLDNAMES

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: libwcs
          path: |
            wcslib-8.3/C/libwcs.dll.8.3
          retention-days: 7
